server:
  port: 9857
spring:
  profiles:
    include: MC
  application:
    name: eureka-admin
  boot:
    admin:
      client:
        enabled: false # 是否注册，默认true
      ui:
        title: "微服务监控"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8848/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: '*' # 生产环境慎用*
  endpoint:
    health:
      show-details: ALWAYS