server:
  port: 9857
spring:
  profiles:
    include: MC
  application:
    name: eureka-admin
  boot:
    admin:
      ui:
        title: "微服务监控"
  security:
    user:
      name: "admin"
      password: "admin"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8848/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
management:
  endpoints:
    web:
      exposure:
        include: '*' # 生产环境慎用*
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file:
    name: simulated-monitor/sbaServer/sbaServer-info.log
    path: simulated-monitor/sbaServer/
