server:
  port: 9857
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  profiles:
    include: MC
  application:
    name: eureka-admin
  boot:
    admin:
      ui:
        title: "微服务监控"
      discovery:
        ignored-services: "*admin"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8848/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: '*' # 生产环境慎用*
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file:
    name: simulated-monitor/sbaServer/sbaServer-info.log
    path: simulated-monitor/sbaServer/
